name: Publish to nuget
on:
  push:
    branches:
      - master # Your default release branch
jobs:
  publish:
    name: publish to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
        
      # Publish
      - name: Publish NuGet
        uses: rohith/publish-nuget@v2.0.0
        with:
           project_dir: Swashbuckle.Rebase.Extensions
           tag_format: v*
           nuget_key: ${{secrets.NUGET_API_KEY}}
